# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.ssh.insert_key = false
  # 'mount_options' used due to 'ansible.cfg' being in world-writable directory:
  # https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
  config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=775"]

  config.vm.define "controller", primary: true do |machine|
    machine.vm.network "private_network", ip: "192.168.33.10"
    machine.vm.hostname = "controller"
    machine.vm.boot_timeout = 420

    machine.vm.provider "virtualbox" do |vb|
      vb.name ="controller"
      vb.memory = "2048"
      vb.cpus = "2"
    end
  end

end
