# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.ssh.insert_key = false
  # 'mount_options' used due to 'ansible.cfg' being in world-writable directory:
  # https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
  config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=775"]
  $msg = <<-'MSG'
  --------------------------------------------------------
  `vagrant ssh controller` to connect to the controller.
  Once connected, use `cd /vagrant` to change to the
  Vagrant project folder.
  From here ansible will have access to playbooks within
  the project.
  --------------------------------------------------------
  MSG
  config.vm.post_up_message = $msg

  config.vm.define "controller", primary: true do |machine|
    machine.vm.network "private_network", ip: "192.168.33.10"
    machine.vm.hostname = "controller"
    machine.vm.boot_timeout = 420

    machine.vm.provider "virtualbox" do |vb|
      vb.name ="controller"
      vb.memory = "2048"
      vb.cpus = "2"
    end

    machine.vm.provision "shell" do |provision|
      provision.path = "provision_ansible.sh"
    end

    # Generate a key pair if one does not exist, and copy public key to shared directory on host machine.
    # Nodes will pull this key for authentication.
    # From: https://github.com/jminck/vagrant-ansible-lab/blob/master/Vagrantfile
    machine.vm.provision :shell, :inline => <<'EOF'
if [ ! -f "/home/vagrant/.ssh/id_rsa" ]; then
  ssh-keygen -t rsa -N "" -f /home/vagrant/.ssh/id_rsa
fi
cp /home/vagrant/.ssh/id_rsa.pub /vagrant/.vagrant/control.pub

chown -R vagrant:vagrant /home/vagrant/.ssh
EOF
  end

  config.vm.define "vagrant1" do |vagrant1|
    vagrant1.vm.hostname = "vagrant1"
    vagrant1.vm.network "private_network", ip: "192.168.33.30"
    vagrant1.vm.network "forwarded_port", id: 'http', guest: 80, host: 8080, host_ip: "127.0.0.1"
    vagrant1.vm.network "forwarded_port", id: 'https', guest: 443, host: 8443, host_ip: "127.0.0.1"

    vagrant1.vm.provider "virtualbox" do |vb|
      vb.name = "vagrant1"
      vb.memory = "1024"
      vb.cpus = "1"
    end

    # Copy the key from the host machine
    vagrant1.vm.provision :shell, inline: 'cat /vagrant/.vagrant/control.pub >> /home/vagrant/.ssh/authorized_keys'
  end

  config.vm.define "vagrant2" do |vagrant2|
    vagrant2.vm.hostname = "vagrant2"
    vagrant2.vm.network "private_network", ip: "192.168.33.40"
    vagrant2.vm.network "forwarded_port", id: 'http', guest: 80, host: 8081, host_ip: "127.0.0.1"
    vagrant2.vm.network "forwarded_port", id: 'https', guest: 443, host: 8444, host_ip: "127.0.0.1"

    vagrant2.vm.provider "virtualbox" do |vb|
      vb.name = "vagrant2"
      vb.memory = "1024"
      vb.cpus = "1"
    end

    # Copy the key from the host machine
    vagrant2.vm.provision :shell, inline: 'cat /vagrant/.vagrant/control.pub >> /home/vagrant/.ssh/authorized_keys'
  end

  config.vm.define "vagrant3" do |vagrant3|
    vagrant3.vm.hostname = "vagrant3"
    # vagrant3.vm.box = "centos/stream8"  ## Download may be blocked at work
    vagrant3.vm.network "private_network", ip: "192.168.33.50"
    vagrant3.vm.network "forwarded_port", id: 'http', guest: 80, host: 8082, host_ip: "127.0.0.1"
    vagrant3.vm.network "forwarded_port", id: 'https', guest: 443, host: 8445, host_ip: "127.0.0.1"

    vagrant3.vm.provider "virtualbox" do |vb|
      vb.name = "vagrant3"
      vb.memory = "1024"
      vb.cpus = "1"
    end

    # Copy the key from the host machine
    vagrant3.vm.provision :shell, inline: 'cat /vagrant/.vagrant/control.pub >> /home/vagrant/.ssh/authorized_keys'
  end

end
