# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Use the default insecure key for these machines
  config.ssh.insert_key = false
  # Forward ssh-agent for cloning from Github.com
  config.ssh.forward_agent = true

  $msg = <<-'MSG'
  --------------------------------------------------------
  `vagrant ssh controller` to connect to the controller.
  Once connected, use `cd /vagrant` to change to the
  Vagrant project folder.
  From here ansible will have access to playbooks within
  the project.
  --------------------------------------------------------
  MSG
  config.vm.post_up_message = $msg

  config.vm.define "controller", primary: true do |controller|
    controller.vm.box = "ubuntu/focal64"
    controller.vm.network "private_network", ip: "192.168.56.10"
    controller.vm.hostname = "controller"
    controller.vm.boot_timeout = 420
    # 'mount_options' used due to 'ansible.cfg' being in world-writable directory:
    # https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
    controller.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=775"]

    controller.vm.provider "virtualbox" do |vb|
      vb.name ="controller"
      vb.memory = "2048"
      vb.cpus = "2"
    end

    controller.vm.provision "shell" do |provision|
      provision.path = "provision_ansible.sh"
    end

    # Generate a key pair if one does not exist, and copy public key to shared directory on host machine.
    # Nodes will pull this key for authentication.
    # From: https://github.com/jminck/vagrant-ansible-lab/blob/master/Vagrantfile
#     controller.vm.provision :shell, :inline => <<'EOF'
# if [ ! -f "/home/vagrant/.ssh/id_rsa" ]; then
#   ssh-keygen -t rsa -N "" -f /home/vagrant/.ssh/id_rsa
# fi
# cp /home/vagrant/.ssh/id_rsa.pub /vagrant/.vagrant/control.pub

# chown -R vagrant:vagrant /home/vagrant/.ssh
# EOF
  end

  config.vm.define "win2022" do |win2022|
    # Windows host
    win2022.vm.box = "jborean93/WindowsServer2022"
    win2022.vm.boot_timeout = 600
    win2022.vm.communicator = "winrm"
    win2022.vm.guest = "windows"
    win2022.vm.hostname = "win2022"
    #win2022.vm.network "forwarded_port", guest: 3389, host: 43389, id: 'rdp', auto_correct: true
    #win2022.vm.network "forwarded_port", guest: 5986, host: 45986, id: 'winrms', auto_correct: false
    win2022.winrm.password = "vagrant"
    win2022.winrm.username = "vagrant"

    # Use the default insecure key for these machines
    win2022.ssh.insert_key = false
    # Forward ssh-agent for cloning from Github.com
    win2022.ssh.forward_agent = true
    # disable updating guest additions
    if Vagrant.has_plugin?("vagrant-vbguest")
      win2022.vbguest.auto_update = false
    end
    
    win2022.vm.network "private_network", ip: "192.168.56.20"
    # win2022.vm.network "forwarded_port", id: 'http', guest: 80, host: 8080, host_ip: "127.0.0.1"
    # win2022.vm.network "forwarded_port", id: 'https', guest: 443, host: 8443, host_ip: "127.0.0.1"

    win2022.vm.provider "virtualbox" do |vb|
      vb.name = "win2022"
      vb.memory = "4096"
      vb.cpus = "4"
      vb.default_nic_type = "virtio"
      vb.gui = true
      vb.customize [
        "modifyvm", :id,
        "--audio", "none",
        "--graphicscontroller", "VBoxSVGA",
        "--natdnshostresolver1", "on",
        "--cableconnected1", "on",
      ]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end

    # Copy the key from the host machine
    # win2022.vm.provision :shell, inline: 'cat /vagrant/.vagrant/control.pub >> /home/vagrant/.ssh/authorized_keys'
  end

end
